name: use
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pyside6=6.9.2
  - numpy=1.26.4
  - opencv=4.8.1
  - pillow=11.3.0
  - psutil=5.9.8
  - requests=2.32.5
  - aiohttp=3.12.15
  - websockets=12.0
  - qasync=0.28.0
  - pip
  - setuptools
  - wheel
  - pip:
      - windows-capture==1.5.0
